version: '3.7'
services:
  webapp:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/home/jovyan/work
    ports:
      # 8888 for jupyter notebook
      - "8888:8888"
      - "9000:9000"
    command: ["jupyter", "notebook"]
